# Generated by Django 3.2.9 on 2021-12-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actiune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filmul', models.CharField(max_length=100)),
                ('Nota', models.IntegerField()),
                ('Nume', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comedie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filmul', models.CharField(max_length=100)),
                ('Nota', models.IntegerField()),
                ('Nume', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Horror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Filmul', models.CharField(max_length=100)),
                ('Nota', models.IntegerField()),
                ('Nume', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
