# Generated by Django 3.2.9 on 2021-12-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nume', models.CharField(max_length=20)),
                ('Filmul', models.CharField(max_length=100)),
                ('Nota', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
